2020-04-02 13:27:56,179 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:46]
2020-04-03 10:09:16,204 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:46]
2020-04-03 10:10:45,127 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:46]
2020-04-03 12:36:29,858 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:47]
2020-04-03 12:52:20,048 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:47]
2020-04-03 12:54:50,413 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:47]
2020-04-03 13:15:07,376 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:47]
2020-04-03 13:15:40,114 ERROR: Exception on /follow/susan [GET] [in d:\perso\web\flask_project\flask_exercice\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\perso\web\flask_project\flask_exercice\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\perso\web\flask_project\flask_exercice\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "d:\perso\web\flask_project\flask_exercice\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "d:\perso\web\flask_project\flask_exercice\lib\site-packages\flask\app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-04-03 13:19:01,554 INFO: Microblog startup [in D:\perso\web\flask_project\flask_exercice\app\__init__.py:47]
